version: "3"

networks:
    dev_backend:

services:
    dev_backend:
        container_name: dev_backend
        build:
            context: .
            dockerfile: dev_backend.Dockerfile
        image: dev_backend:1.0
        command: python manage.py runserver 0:8000
        env_file: dev_backend.env
        networks:
            - dev_backend
        ports:
            - 80:8000
        volumes:
            - ./:/usr/nupe
